name: PR-Validation-powershell-core
on:
  pull_request:

env:
  WindowsName: windows
  WindowsAgentPoolName: pool-windows-2019
  WindowsAgentPoolVMImage: ''
  LinuxName: linux
  LinuxAgentPoolName: pool-ubuntu-2004
  LinuxAgentPoolVMImage: ''
  MacOSName: macOS
  MacOSAgentPoolName: 'Azure Pipelines'
  MacOSAgentPoolVMImage: macOS-latest
  TestFramework: net6.0
  TestTarget: Test
  Configuration: Debug
  DebugLocalBuildTasks: true
  IsGenerateBased: ${{ startsWith(github.base_ref, 'generation') }}
  BuildTimeoutInMinutes: 120
  AnalysisTimeoutInMinutes: 120
  TestTimeoutInMinutes: 180
  BuildAzPredictor: false
  EnableTestCoverage: true
  TestCoverageLocation: $(Build.SourcesDirectory)/artifacts
  PowerShellPlatform: PowerShell Core
  AZURE_CLIENTS_SHOW_SECRETS_WARNING: true
  
jobs:

  Build:
    runs-on: windows-latest
    steps:
    - shell: pwsh
      run: |
        dir env:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/workflows/pr-build-steps
      with:
        configuration: ${{ env.Configuration }}
        testFramework: ${{ env.TestFramework }}
        powerShellPlatform: ${{ env.PowerShellPlatform }}
